version: '3.9'

services:
  db:
    container_name: db
    image: mysql:8.0.34
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wiki_local
      MYSQL_USER: wiki
      MYSQL_PASSWORD: password
    restart:
      always
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    ports:
      - 8080:8080
    depends_on:
      - db
    command: ["reflex", "-r", "^(cmd|pkg)/.*.go$", "-s", "go", "run", "./cmd/nullwiki/wiki.go"]
    volumes:
      - .:/app:cached
