version: '3.9'

services:
  mysql:
    image: mysql:8.0.34
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wiki_local
      MYSQL_USER: wiki
      MYSQL_PASSWORD: password
    restart:
      always
