// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (pa *Page) Owner(ctx context.Context) (*User, error) {
	result, err := pa.Edges.OwnerOrErr()
	if IsNotLoaded(err) {
		result, err = pa.QueryOwner().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (u *User) Pages(ctx context.Context) (result []*Page, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = u.NamedPages(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = u.Edges.PagesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = u.QueryPages().All(ctx)
	}
	return result, err
}
